[font]
size = 11.0

[font.bold]
family = "Fira Code"
style = "Semibold"

[font.bold_italic]
family = "Fira Code"
style = "Bold Italic"

[font.italic]
family = "Fira Code"
style = "Italic"

[font.normal]
family = "Fira Code"
style = "Regular"

[scrolling]
history = 10000

[shell]
program = "/bin/fish"

[window]
dynamic_title = true
opacity = 0.9
